export const EventType = {
    O_EVENT_TASK_STATUS: "O_EVENT_TASK_STATUS",
    O_EVENT_BUS_REQ: "O_EVENT_BUS_REQ",

    O_EVENT_HOOK_REQ: "O_EVENT_HOOK_REQ",
    O_EVENT_USER_NOTIFY: "O_EVENT_USER_NOTIFY",
    O_EVENT_USER_INPUT: "O_EVENT_USER_INPUT",
    O_EVENT_WINDOW_REQ: "O_EVENT_WINDOW_REQ",

    O_EVENT_WSS_REQ: "O_EVENT_WSS_REQ",
    I_EVENT_TASK_REQ: "I_EVENT_TASK_REQ",
    I_EVENT_WSS_REQ: "I_EVENT_WSS_REQ",
};