export const EventType = {
    O_EVENT_TASK_STATUS: "O_EVENT_TASK_STATUS",
    O_EVENT_REG_EVENT_ON: "O_EVENT_REG_EVENT_ON",
    O_EVENT_REG_EVENT_REMOVE: "O_EVENT_REG_EVENT_REMOVE",
    O_EVENT_REG_EVENT_INVOKE: "O_EVENT_REG_EVENT_INVOKE",

    O_EVENT_HOOK_REQ: "O_EVENT_HOOK_REQ",
    O_EVENT_USER_NOTIFY: "O_EVENT_USER_NOTIFY",

    I_EVENT_TASK_REQ: "I_EVENT_TASK_REQ",
};